#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"


# ==============================================================================
# System Integrity Protection Non-Compliant Commands
# ==============================================================================
#
# Focus Space
# ------------------------------------------------------------------------------
# # Focus space focused before the current one (so you can alternate)
# yabai -m space --focus recent
#
# # Focus previous space by mission-control index
# yabai -m space --focus prev
#
# # Focus next space by mission-control index
# yabai -m space --focus next
#
# # Focus space with mission-control index 2
# yabai -m space --focus 2
#
# # Focus next space by mission-control index if one exists, otherwise focus the
#   first space
# yabai -m space --focus next || yabai -m space --focus first
#
# # Focus previous space by mission-control index if one exists, otherwise focus
#   the last space
# yabai -m space --focus prev || yabai -m space --focus last
# ------------------------------------------------------------------------------
#
# Create/Destroy Space
# ------------------------------------------------------------------------------
# # Create space on the active display
# yabai -m space --create
#
# # Delete focused space and focus first space on display
# yabai -m space --destroy
# ------------------------------------------------------------------------------
#
# Move Space
# ------------------------------------------------------------------------------
# # Move space left
# yabai -m space --move prev
#
# # Move space right
# yabai -m space --move next
#
# # Send space to display 2 (by display arrangement index)
# yabai -m space --display 2
# ------------------------------------------------------------------------------


# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement             second_child
yabai -m config window_topmost               on

# System Integrity Protection Non-Compliant Settings
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f

yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# Window Padding settings
yabai -m config layout                       bsp
# yabai -m config top_padding                  12
# yabai -m config bottom_padding               12
# yabai -m config left_padding                 12
# yabai -m config right_padding                12
yabai -m config window_gap                   03


# Windows that should always be in a floating window
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Keepass.*" sticky=on layer=above manage=off
yabai -m rule --add app="^Installer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Calculator$" sticky=on layer=above manage=off
yabai -m rule --add app="^Font Book$" sticky=on layer=above manage=off
yabai -m rule --add app="^Cisco AnyConnect Secure Mobility Client$" sticky=on layer=above manage=off

killall limelight &> /dev/null
limelight &> /dev/null &

# When a window is closed, move focus to the window closest to the mouse
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

echo "yabai configuration loaded.."
