#!/usr/bin/env zsh

# If not running interactively, don't do anything
case "$-" in
    *i*) ;;
    *)   return ;;
esac

# Prompt {{{
zmodule romkatv/powerlevel10k --use degit
# Prompt }}}

# Oh My Zsh Plugins {{{

# If a command was not found, mention some similarly names commands that could
# be downloaded
zmodule ohmyzsh/ohmyzsh --root plugins/command-not-found

# Interactive cd
zmodule ohmyzsh/ohmyzsh --root plugins/zsh-interactive-cd

# zmodule ohmyzsh/ohmyzsh --root plugins/vim-interaction
zmodule ohmyzsh/ohmyzsh --root plugins/fzf
bindkey -r '^T'
bindkey '^P' fzf-file-widget

# Oh My Zsh Plugins }}}

# Completions {{{

# Enables and configures smart and extensive tab completion.
# completion must be sourced after all modules that add completion definitions.
zmodule completion

zmodule zsh-users/zsh-completions --fpath src

# Add gradle autocompletion
zmodule gradle/gradle-completion
local gradle_completion_path="$ZIM_HOME/modules/gradle-completion"
if ! (($fpath[(Ie)$gradle_completion_path])); then
    fpath=("$ZIM_HOME/modules/gradle-completion" $fpath)
fi


# Completions }}}

# Modules that need to be initialized last {{{
    # Provide command autosuggestions. This should be defered before syntax
    # hightlighting.
    #
    # See: https://github.com/zsh-users/zsh-autosuggestions
    zmodule zsh-users/zsh-autosuggestions
    ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=7'

    # Syntax Hightlighting. Must be sourced after compinit
    #
    # See: https://github.com/zsh-users/zsh-autosuggestions
    zmodule zdharma-continuum/fast-syntax-highlighting
# Modules that need to be initialized last }}}
